In [11]:
import numpy as np
data = np.loadtxt('data/model_forecasts.txt', delimiter=',')
print(data.shape)
print(data)

(10, 10)
[[  nan -2.3  -4.59 -4.83  3.13  4.13  1.07  2.29  0.44  4.35]
 [ 2.3    nan  3.57 -4.66  2.3  -3.24  3.63  0.41 -2.   -0.77]
 [ 4.59 -3.57   nan  1.47  1.15 -1.16  4.97  4.81  1.86  1.5 ]
 [ 4.83  4.66 -1.47   nan  0.25 -1.9  -0.14  3.89  4.34 -1.42]
 [-3.13 -2.3  -1.15 -0.25   nan  3.9  -2.73  1.23 -4.16  3.33]
 [-4.13  3.24  1.16  1.9  -3.9    nan -0.5   2.96 -2.69 -4.48]
 [-1.07 -3.63 -4.97  0.14  2.73  0.5    nan  4.42 -1.35 -3.95]
 [-2.29 -0.41 -4.81 -3.89 -1.23 -2.96 -4.42   nan  4.49 -0.4 ]
 [-0.44  2.   -1.86 -4.34  4.16  2.69  1.35 -4.49   nan  2.29]
 [-4.35  0.77 -1.5   1.42 -3.33  4.48  3.95  0.4  -2.29   nan]]


In [14]:
import itertools

In [12]:
teams = np.arange(10)
print(teams)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
permutations = np.array(list(itertools.permutations(teams)))
print(permutations)
print(permutations.shape)

[[0 1 2 ... 7 8 9]
 [0 1 2 ... 7 9 8]
 [0 1 2 ... 8 7 9]
 ...
 [9 8 7 ... 1 2 0]
 [9 8 7 ... 2 0 1]
 [9 8 7 ... 2 1 0]]
(3628800, 10)


In [31]:
team1 = permutations[:, 0::2]  # columns 0,2,4,6,8
team2 = permutations[:, 1::2]  # columns 1,3,5,7,9

print(team1.shape)
print(team2.shape)

(3628800, 5)
(3628800, 5)


In [39]:
differences = data[team1, team2]
print(differences)
print(differences.shape)

[[-2.3   1.47  3.9   4.42  2.29]
 [-2.3   1.47  3.9   4.42 -2.29]
 [-2.3   1.47  3.9  -1.35 -0.4 ]
 ...
 [-2.29 -4.42 -3.9   4.66  4.59]
 [-2.29 -4.42 -3.9  -1.47 -2.3 ]
 [-2.29 -4.42 -3.9  -1.47  2.3 ]]
(3628800, 5)


In [40]:
scores = np.sum(differences ** 2, axis=1)
print(scores)
print(scores.shape)

[47.4414 47.4414 24.6434 ... 82.7742 47.4414 47.4414]
(3628800,)


In [37]:
best_index = np.argmin(scores) # index of the smallest value
best_pairing = permutations[best_index]  # the smallest value itself
print(best_pairing)

[0 8 1 7 2 9 3 4 5 6]


In [38]:
result = best_pairing.reshape(2, 5, order='F') # fortrone
print(result)

[[0 1 2 3 5]
 [8 7 9 4 6]]
