In [2]:
import numpy as np

In [4]:
# se seed
np.random.seed(888)

In [6]:
# 1D array, size 100, normal distribution
normal_array = np.random.randn(100)
print(normal_array)

[-0.07709578  0.11726715  0.27025277 -0.58366313 -1.59306943 -0.96499503
  0.77776558  0.5147422   1.43145716  0.36811156  0.45166194  0.29363375
 -1.0826927  -0.58007176  0.85113031  1.17101233  1.23707973 -0.5142449
 -1.05149287 -0.35738287 -0.20687447  0.27985759 -1.40777268  0.98351332
  0.20283536 -0.48134655  1.43122811  0.33655721 -0.25367467 -0.71431213
 -1.3183988  -0.48975812  2.12003625 -2.11468423 -2.63576433  1.72353902
 -0.22564201  0.76006445 -0.88091651 -0.2529336   1.41197056 -1.80925916
 -0.85439975 -1.04018941  0.11445591  0.38828076  0.34751399 -0.20199612
  0.23486733 -0.43546532  0.10231181  0.0441651  -1.27296178  0.39756296
  2.407855    1.3017182  -1.32527458  1.68760536  0.411356    1.52626108
  0.14575703  0.3132854   0.16435966  0.13652497  0.39296835  0.17063542
 -0.7662608  -0.95152711 -1.50133434  0.45446246  0.69009994 -0.96058718
 -0.82834378  0.66744863 -1.55593018 -1.40452004  0.59710818 -1.45831432
  0.24254733 -0.42707128  0.90154539  0.77946282 -0.

In [9]:
# Q3 - 2D array 8x8, random integers 1 to 10 inclusive
int_2d = np.random.randint(1, 11, size=(8, 8))
print(int_2d)

[[ 4 10  6  9  6  9  1  5]
 [ 9  7  7  8  5  6 10  1]
 [ 4  9  5  2  9  7  5  1]
 [ 4  4 10  1  8  2  1  7]
 [ 1  7  1  4  9  4  6  1]
 [ 3  6  6  6  3  8  7  2]
 [ 2  5  6  6  2  1  1  4]
 [ 1  7  9  1  7  6 10  5]]


In [10]:
# Q4 - 3D array 4x2x5, random integers 1 to 17 inclusive
int_3d = np.random.randint(1, 18, size=(4, 2, 5))
print(int_3d)

[[[12 13 15 14  7]
  [11 17 10  8 15]]

 [[ 4  7 12  6 14]
  [11  5 16 16  5]]

 [[ 1 13 14 16 13]
  [16 14  5 17 16]]

 [[10  2 12  5 15]
  [ 5 16  1 10  1]]]
