In [5]:
import numpy as np

In [4]:
a = np.full((9,9), 1,  dtype = np.int8)
print(a)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [8]:
a[1:8, 1:8] = 0 
a[2:7, 2:7] = 1 
a[3:6, 3:6] = 0
a[4, 4]     = 1 
print(a)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [18]:
array_1  = np.array([1,2,3,4,5] , dtype = np.int8)
array_2 = np.array([1,2,3], dtype = np.int8)

result = array_1.reshape(5,1) * array_2
print(result)

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]
